version: '2'

services:
  wst_analyzer:
    build: 
      context: .
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
        - no_proxy
    environment:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
        - no_proxy
    ports:
      - "5000:5000"
    volumes:
      - .:/code